---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-certificate
  namespace: default
spec:
  secretName: dev-tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - dev.vishnuvpm.tech
